In [1]:
import matplotlib.pyplot as plt
from keras import Model
from keras.layers import Dense
from keras_pandas.Automater import Automater
from keras.models import model_from_json
from keras import backend as K
from  sklearn.utils import resample
import functools
import pandas
import tensorflow as tf
import numpy as np
from tensorflow.python.saved_model import builder as saved_model_builder
from tensorflow.python.saved_model import tag_constants, signature_constants, signature_def_utils_impl

/home/fuckme/.local/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [5]:
df=pandas.DataFrame({"hey":["dogs"],"es":["cats"]})
df

es   hey
0  cats  dogs

In [66]:
df=pandas.read_csv('Logs/stats.csv')


In [67]:
df['target'] = df.apply (lambda row: row["Opponent_Percent_Change"]>0 ,axis=1)

In [86]:
df_test=df.head(1)

<class 'pandas.core.frame.DataFrame'>


In [87]:
df=df_test.append([df_test.head(1)]*150,ignore_index=True)

In [88]:
print(df)

     Frame  Opponent_x  Opponent_y  AI_x  AI_y  Opponent_Facing  AI_Facing  \
0        1       -70.0         7.0  70.0   7.0             True      False   
1        1       -70.0         7.0  70.0   7.0             True      False   
2        1       -70.0         7.0  70.0   7.0             True      False   
3        1       -70.0         7.0  70.0   7.0             True      False   
4        1       -70.0         7.0  70.0   7.0             True      False   
5        1       -70.0         7.0  70.0   7.0             True      False   
6        1       -70.0         7.0  70.0   7.0             True      False   
7        1       -70.0         7.0  70.0   7.0             True      False   
8        1       -70.0         7.0  70.0   7.0             True      False   
9        1       -70.0         7.0  70.0   7.0             True      False   
10       1       -70.0         7.0  70.0   7.0             True      False   
11       1       -70.0         7.0  70.0   7.0             True 

In [89]:
df['Buttons_Pressed_Converted'] = df.apply (lambda row:row.name,axis=1)

In [90]:
df

Frame  Opponent_x  Opponent_y  AI_x  AI_y  Opponent_Facing  AI_Facing  \
0        1       -70.0         7.0  70.0   7.0             True      False   
1        1       -70.0         7.0  70.0   7.0             True      False   
2        1       -70.0         7.0  70.0   7.0             True      False   
3        1       -70.0         7.0  70.0   7.0             True      False   
4        1       -70.0         7.0  70.0   7.0             True      False   
5        1       -70.0         7.0  70.0   7.0             True      False   
6        1       -70.0         7.0  70.0   7.0             True      False   
7        1       -70.0         7.0  70.0   7.0             True      False   
8        1       -70.0         7.0  70.0   7.0             True      False   
9        1       -70.0         7.0  70.0   7.0             True      False   
10       1       -70.0         7.0  70.0   7.0             True      False   
11       1       -70.0         7.0  70.0   7.0             True      False   
12       1       -70.0         7.0  70.0   7.0             True      False   
13       1       -70.0         7.0  70.0   7.0             True      False   
14       1       -70.0         7.0  70.0   7.0             True      False   
15       1       -70.0         7.0  70.0   7.0             True      False   
16       1       -70.0         7.0  70.0   7.0             True      False   
17       1       -70.0         7.0  70.0   7.0             True      False   
18       1       -70.0         7.0  70.0   7.0             True      False   
19       1       -70.0         7.0  70.0   7.0             True      False   
20       1       -70.0         7.0  70.0   7.0             True      False   
21       1       -70.0         7.0  70.0   7.0             True      False   
22       1       -70.0         7.0  70.0   7.0             True      False   
23       1       -70.0         7.0  70.0   7.0             True      False   
24       1       -70.0         7.0  70.0   7.0             True      False   
25       1       -70.0         7.0  70.0   7.0             True      False   
26       1       -70.0         7.0  70.0   7.0             True      False   
27       1       -70.0         7.0  70.0   7.0             True      False   
28       1       -70.0         7.0  70.0   7.0             True      False   
29       1       -70.0         7.0  70.0   7.0             True      False   
..     ...         ...         ...   ...   ...              ...        ...   
120      1       -70.0         7.0  70.0   7.0             True      False   
121      1       -70.0         7.0  70.0   7.0             True      False   
122      1       -70.0         7.0  70.0   7.0             True      False   
123      1       -70.0         7.0  70.0   7.0             True      False   
124      1       -70.0         7.0  70.0   7.0             True      False   
125      1       -70.0         7.0  70.0   7.0             True      False   
126      1       -70.0         7.0  70.0   7.0             True      False   
127      1       -70.0         7.0  70.0   7.0             True      False   
128      1       -70.0         7.0  70.0   7.0             True      False   
129      1       -70.0         7.0  70.0   7.0             True      False   
130      1       -70.0         7.0  70.0   7.0             True      False   
131      1       -70.0         7.0  70.0   7.0             True      False   
132      1       -70.0         7.0  70.0   7.0             True      False   
133      1       -70.0         7.0  70.0   7.0             True      False   
134      1       -70.0         7.0  70.0   7.0             True      False   
135      1       -70.0         7.0  70.0   7.0             True      False   
136      1       -70.0         7.0  70.0   7.0             True      False   
137      1       -70.0         7.0  70.0   7.0             True      False   
138      1       -70.0         7.0  70.0   7.0             True      False   
139      1       -70.0     

In [91]:
categorical_vars=["Opponent_Facing","AI_Facing","target"]
numerical_vars=["Frame","Opponent_x","Opponent_y","AI_x","AI_y",
                "Opponent_Action_Num","AI_Action_Num","AI_Action_Frame",
                "Opponent_Action_Frame","Opponent_Jumps_Left", "AI_Jumps_Left",
                "Opponent_Stock","AI_Stock",
                "Opponent_Percent","AI_Percent","Buttons_Pressed_Converted"]
auto=Automater(categorical_vars=categorical_vars,numerical_vars=numerical_vars,response_var="target")

In [93]:
X, y = auto.fit_transform(df)

/home/fuckme/.local/lib/python3.5/site-packages/sklearn/preprocessing/label.py:95: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/fuckme/.local/lib/python3.5/site-packages/sklearn/preprocessing/label.py:128: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/fuckme/.local/lib/python3.5/site-packages/keras_pandas/constants.py:32: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  transformed = input_dataframe[variable].as_matrix()
/home/fuckme/.local/lib/python3.5/site-packages/keras_pandas/constants.py:49: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  transformed = input_dataframe[variable].as_matrix()


In [94]:
json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)

In [95]:
loaded_model.load_weights("my_model_weights.h5")

In [39]:
X

[array([-1.34299054, -1.03815563, -0.98707218, ...,  0.25669868,
         0.35775506,  0.4249409 ]),
 array([ 1.50358972, -1.39719315, -0.98861326, ...,  1.46184421,
         1.59462595,  1.7116878 ]),
 array([ 1.08919247, -0.53450696, -0.07186727, ..., -0.53678419,
        -0.53450696, -0.53450696]),
 array([ 1.02399651, -1.9538376 , -1.06177636, ...,  1.36608789,
         1.69865204,  2.03738499]),
 array([ 1.31652434, -0.49840043, -0.54799669, ..., -0.54799669,
        -0.54799669,  0.0204874 ]),
 array([-0.17835788, -0.23448476, -0.15029444, ..., -0.20642132,
        -0.20642132, -0.20642132]),
 array([-0.07042754,  1.36756953,  1.19656448, ...,  0.18608005,
        -1.03427422,  1.36756953]),
 array([ 2.04442788, -0.77237066,  0.63602861, ..., -0.06817102,
         0.81207852, -0.94842057]),
 array([-0.06844643, -0.06844643, -0.06844643, ..., -0.06844643,
        -0.06844643, -0.06844643]),
 array([-0.06937681, -0.06937681, -0.06937681, ..., -0.06937681,
        -0.06937681, -0.06

In [96]:
loaded_model.predict(X)

array([[0.602085  , 0.39791504],
       [0.6019668 , 0.39803317],
       [0.6018486 , 0.3981514 ],
       [0.60173035, 0.39826962],
       [0.60161227, 0.39838776],
       [0.601494  , 0.39850602],
       [0.6013756 , 0.39862442],
       [0.6012573 , 0.39874268],
       [0.60113907, 0.3988609 ],
       [0.6010206 , 0.3989794 ],
       [0.6009025 , 0.3990975 ],
       [0.6007841 , 0.39921594],
       [0.6006657 , 0.3993343 ],
       [0.6005474 , 0.3994526 ],
       [0.60042894, 0.39957103],
       [0.60031074, 0.39968923],
       [0.6001922 , 0.39980778],
       [0.6000739 , 0.39992613],
       [0.59995526, 0.4000447 ],
       [0.5998368 , 0.40016314],
       [0.5997185 , 0.40028155],
       [0.5996001 , 0.40039992],
       [0.5994814 , 0.4005186 ],
       [0.599363  , 0.40063694],
       [0.5992445 , 0.40075555],
       [0.59912604, 0.40087402],
       [0.59900755, 0.40099248],
       [0.598889  , 0.40111104],
       [0.5987705 , 0.4012295 ],
       [0.598652  , 0.40134802],
       [0.